### PR TITLE
added lowerCaseChar, upperCaseChar, anyLetter and alphaNum

### PR DESCRIPTION
**Pull request by Thimoteus**

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Hey, @paf31, can this be merged?

It also fixes broken behavior of `whiteSpaces`.

**Comment by paf31** [comment]
Yes, sorry I missed this. Thanks!

**Comment by chrisdotcode** [comment]
Don't forget the version++

**Comment by paf31** [comment]
Already done, 0.6.5.

**Pull request merged**
